# file: k8s-api/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: demo
spec:
  project: default
  selector:
    matchLabels: { app: api }
  endpoints:
  - { port: http, path: /metrics, interval: 15s }
